/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyRouteImport } from './routes/why'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProblemRouteImport } from './routes/problem'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as LegalSlugRouteImport } from './routes/legal.$slug'
import { Route as ConstructionSlugRouteImport } from './routes/construction.$slug'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardSupplierOnboardingRouteImport } from './routes/_authenticated/dashboard.supplier-onboarding'
import { Route as AuthenticatedDashboardSupplierRouteImport } from './routes/_authenticated/dashboard.supplier'
import { Route as AuthenticatedDashboardProfessionalRouteImport } from './routes/_authenticated/dashboard.professional'
import { Route as AuthenticatedDashboardClientRouteImport } from './routes/_authenticated/dashboard/client'
import { Route as AuthenticatedDashboardCalculatorRouteImport } from './routes/_authenticated/dashboard.calculator'
import { Route as AuthenticatedDashboardBuilderRouteImport } from './routes/_authenticated/dashboard.builder'
import { Route as AuthenticatedDashboardArtisanRouteImport } from './routes/_authenticated/dashboard.artisan'
import { Route as AuthenticatedDashboardAdminSuppliersRouteImport } from './routes/_authenticated/dashboard.admin-suppliers'
import { Route as AuthenticatedDashboardAdminSettingsRouteImport } from './routes/_authenticated/dashboard.admin-settings'
import { Route as AuthenticatedDashboardAdminDisputesRouteImport } from './routes/_authenticated/dashboard.admin-disputes'
import { Route as AuthenticatedDashboardAdminBoqRouteImport } from './routes/_authenticated/dashboard.admin-boq'
import { Route as AuthenticatedDashboardAdminRouteImport } from './routes/_authenticated/dashboard.admin'
import { Route as AuthenticatedDashboardProjectsProjectIdRouteImport } from './routes/_authenticated/dashboard.projects.$projectId'
import { Route as AuthenticatedDashboardBoqRequestProjectIdRouteImport } from './routes/_authenticated/dashboard.boq-request.$projectId'
import { Route as AuthenticatedDashboardClientProjectsNewRouteImport } from './routes/_authenticated/dashboard/client/projects/new'

const WhyRoute = WhyRouteImport.update({
  id: '/why',
  path: '/why',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemRoute = ProblemRouteImport.update({
  id: '/problem',
  path: '/problem',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstructionSlugRoute = ConstructionSlugRouteImport.update({
  id: '/construction/$slug',
  path: '/construction/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardSupplierOnboardingRoute =
  AuthenticatedDashboardSupplierOnboardingRouteImport.update({
    id: '/dashboard/supplier-onboarding',
    path: '/dashboard/supplier-onboarding',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardSupplierRoute =
  AuthenticatedDashboardSupplierRouteImport.update({
    id: '/dashboard/supplier',
    path: '/dashboard/supplier',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardProfessionalRoute =
  AuthenticatedDashboardProfessionalRouteImport.update({
    id: '/dashboard/professional',
    path: '/dashboard/professional',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardClientRoute =
  AuthenticatedDashboardClientRouteImport.update({
    id: '/dashboard/client',
    path: '/dashboard/client',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardCalculatorRoute =
  AuthenticatedDashboardCalculatorRouteImport.update({
    id: '/dashboard/calculator',
    path: '/dashboard/calculator',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardBuilderRoute =
  AuthenticatedDashboardBuilderRouteImport.update({
    id: '/dashboard/builder',
    path: '/dashboard/builder',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardArtisanRoute =
  AuthenticatedDashboardArtisanRouteImport.update({
    id: '/dashboard/artisan',
    path: '/dashboard/artisan',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardAdminSuppliersRoute =
  AuthenticatedDashboardAdminSuppliersRouteImport.update({
    id: '/dashboard/admin-suppliers',
    path: '/dashboard/admin-suppliers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardAdminSettingsRoute =
  AuthenticatedDashboardAdminSettingsRouteImport.update({
    id: '/dashboard/admin-settings',
    path: '/dashboard/admin-settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardAdminDisputesRoute =
  AuthenticatedDashboardAdminDisputesRouteImport.update({
    id: '/dashboard/admin-disputes',
    path: '/dashboard/admin-disputes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardAdminBoqRoute =
  AuthenticatedDashboardAdminBoqRouteImport.update({
    id: '/dashboard/admin-boq',
    path: '/dashboard/admin-boq',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardAdminRoute =
  AuthenticatedDashboardAdminRouteImport.update({
    id: '/dashboard/admin',
    path: '/dashboard/admin',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardProjectsProjectIdRoute =
  AuthenticatedDashboardProjectsProjectIdRouteImport.update({
    id: '/dashboard/projects/$projectId',
    path: '/dashboard/projects/$projectId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardBoqRequestProjectIdRoute =
  AuthenticatedDashboardBoqRequestProjectIdRouteImport.update({
    id: '/dashboard/boq-request/$projectId',
    path: '/dashboard/boq-request/$projectId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardClientProjectsNewRoute =
  AuthenticatedDashboardClientProjectsNewRouteImport.update({
    id: '/projects/new',
    path: '/projects/new',
    getParentRoute: () => AuthenticatedDashboardClientRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/impact': typeof ImpactRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/problem': typeof ProblemRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/why': typeof WhyRoute
  '/construction/$slug': typeof ConstructionSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/admin-boq': typeof AuthenticatedDashboardAdminBoqRoute
  '/dashboard/admin-disputes': typeof AuthenticatedDashboardAdminDisputesRoute
  '/dashboard/admin-settings': typeof AuthenticatedDashboardAdminSettingsRoute
  '/dashboard/admin-suppliers': typeof AuthenticatedDashboardAdminSuppliersRoute
  '/dashboard/artisan': typeof AuthenticatedDashboardArtisanRoute
  '/dashboard/builder': typeof AuthenticatedDashboardBuilderRoute
  '/dashboard/calculator': typeof AuthenticatedDashboardCalculatorRoute
  '/dashboard/client': typeof AuthenticatedDashboardClientRouteWithChildren
  '/dashboard/professional': typeof AuthenticatedDashboardProfessionalRoute
  '/dashboard/supplier': typeof AuthenticatedDashboardSupplierRoute
  '/dashboard/supplier-onboarding': typeof AuthenticatedDashboardSupplierOnboardingRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/boq-request/$projectId': typeof AuthenticatedDashboardBoqRequestProjectIdRoute
  '/dashboard/projects/$projectId': typeof AuthenticatedDashboardProjectsProjectIdRoute
  '/dashboard/client/projects/new': typeof AuthenticatedDashboardClientProjectsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/impact': typeof ImpactRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/problem': typeof ProblemRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/why': typeof WhyRoute
  '/construction/$slug': typeof ConstructionSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/admin-boq': typeof AuthenticatedDashboardAdminBoqRoute
  '/dashboard/admin-disputes': typeof AuthenticatedDashboardAdminDisputesRoute
  '/dashboard/admin-settings': typeof AuthenticatedDashboardAdminSettingsRoute
  '/dashboard/admin-suppliers': typeof AuthenticatedDashboardAdminSuppliersRoute
  '/dashboard/artisan': typeof AuthenticatedDashboardArtisanRoute
  '/dashboard/builder': typeof AuthenticatedDashboardBuilderRoute
  '/dashboard/calculator': typeof AuthenticatedDashboardCalculatorRoute
  '/dashboard/client': typeof AuthenticatedDashboardClientRouteWithChildren
  '/dashboard/professional': typeof AuthenticatedDashboardProfessionalRoute
  '/dashboard/supplier': typeof AuthenticatedDashboardSupplierRoute
  '/dashboard/supplier-onboarding': typeof AuthenticatedDashboardSupplierOnboardingRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/boq-request/$projectId': typeof AuthenticatedDashboardBoqRequestProjectIdRoute
  '/dashboard/projects/$projectId': typeof AuthenticatedDashboardProjectsProjectIdRoute
  '/dashboard/client/projects/new': typeof AuthenticatedDashboardClientProjectsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/impact': typeof ImpactRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/problem': typeof ProblemRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/why': typeof WhyRoute
  '/construction/$slug': typeof ConstructionSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/_authenticated/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/_authenticated/dashboard/admin-boq': typeof AuthenticatedDashboardAdminBoqRoute
  '/_authenticated/dashboard/admin-disputes': typeof AuthenticatedDashboardAdminDisputesRoute
  '/_authenticated/dashboard/admin-settings': typeof AuthenticatedDashboardAdminSettingsRoute
  '/_authenticated/dashboard/admin-suppliers': typeof AuthenticatedDashboardAdminSuppliersRoute
  '/_authenticated/dashboard/artisan': typeof AuthenticatedDashboardArtisanRoute
  '/_authenticated/dashboard/builder': typeof AuthenticatedDashboardBuilderRoute
  '/_authenticated/dashboard/calculator': typeof AuthenticatedDashboardCalculatorRoute
  '/_authenticated/dashboard/client': typeof AuthenticatedDashboardClientRouteWithChildren
  '/_authenticated/dashboard/professional': typeof AuthenticatedDashboardProfessionalRoute
  '/_authenticated/dashboard/supplier': typeof AuthenticatedDashboardSupplierRoute
  '/_authenticated/dashboard/supplier-onboarding': typeof AuthenticatedDashboardSupplierOnboardingRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/boq-request/$projectId': typeof AuthenticatedDashboardBoqRequestProjectIdRoute
  '/_authenticated/dashboard/projects/$projectId': typeof AuthenticatedDashboardProjectsProjectIdRoute
  '/_authenticated/dashboard/client/projects/new': typeof AuthenticatedDashboardClientProjectsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/forgot-password'
    | '/impact'
    | '/login'
    | '/onboarding'
    | '/problem'
    | '/reset-password'
    | '/signup'
    | '/why'
    | '/construction/$slug'
    | '/legal/$slug'
    | '/services/$slug'
    | '/dashboard/admin'
    | '/dashboard/admin-boq'
    | '/dashboard/admin-disputes'
    | '/dashboard/admin-settings'
    | '/dashboard/admin-suppliers'
    | '/dashboard/artisan'
    | '/dashboard/builder'
    | '/dashboard/calculator'
    | '/dashboard/client'
    | '/dashboard/professional'
    | '/dashboard/supplier'
    | '/dashboard/supplier-onboarding'
    | '/dashboard/'
    | '/dashboard/boq-request/$projectId'
    | '/dashboard/projects/$projectId'
    | '/dashboard/client/projects/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/forgot-password'
    | '/impact'
    | '/login'
    | '/onboarding'
    | '/problem'
    | '/reset-password'
    | '/signup'
    | '/why'
    | '/construction/$slug'
    | '/legal/$slug'
    | '/services/$slug'
    | '/dashboard/admin'
    | '/dashboard/admin-boq'
    | '/dashboard/admin-disputes'
    | '/dashboard/admin-settings'
    | '/dashboard/admin-suppliers'
    | '/dashboard/artisan'
    | '/dashboard/builder'
    | '/dashboard/calculator'
    | '/dashboard/client'
    | '/dashboard/professional'
    | '/dashboard/supplier'
    | '/dashboard/supplier-onboarding'
    | '/dashboard'
    | '/dashboard/boq-request/$projectId'
    | '/dashboard/projects/$projectId'
    | '/dashboard/client/projects/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/contact'
    | '/forgot-password'
    | '/impact'
    | '/login'
    | '/onboarding'
    | '/problem'
    | '/reset-password'
    | '/signup'
    | '/why'
    | '/construction/$slug'
    | '/legal/$slug'
    | '/services/$slug'
    | '/_authenticated/dashboard/admin'
    | '/_authenticated/dashboard/admin-boq'
    | '/_authenticated/dashboard/admin-disputes'
    | '/_authenticated/dashboard/admin-settings'
    | '/_authenticated/dashboard/admin-suppliers'
    | '/_authenticated/dashboard/artisan'
    | '/_authenticated/dashboard/builder'
    | '/_authenticated/dashboard/calculator'
    | '/_authenticated/dashboard/client'
    | '/_authenticated/dashboard/professional'
    | '/_authenticated/dashboard/supplier'
    | '/_authenticated/dashboard/supplier-onboarding'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/boq-request/$projectId'
    | '/_authenticated/dashboard/projects/$projectId'
    | '/_authenticated/dashboard/client/projects/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ImpactRoute: typeof ImpactRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProblemRoute: typeof ProblemRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  WhyRoute: typeof WhyRoute
  ConstructionSlugRoute: typeof ConstructionSlugRoute
  LegalSlugRoute: typeof LegalSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why': {
      id: '/why'
      path: '/why'
      fullPath: '/why'
      preLoaderRoute: typeof WhyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problem': {
      id: '/problem'
      path: '/problem'
      fullPath: '/problem'
      preLoaderRoute: typeof ProblemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construction/$slug': {
      id: '/construction/$slug'
      path: '/construction/$slug'
      fullPath: '/construction/$slug'
      preLoaderRoute: typeof ConstructionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/supplier-onboarding': {
      id: '/_authenticated/dashboard/supplier-onboarding'
      path: '/dashboard/supplier-onboarding'
      fullPath: '/dashboard/supplier-onboarding'
      preLoaderRoute: typeof AuthenticatedDashboardSupplierOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/supplier': {
      id: '/_authenticated/dashboard/supplier'
      path: '/dashboard/supplier'
      fullPath: '/dashboard/supplier'
      preLoaderRoute: typeof AuthenticatedDashboardSupplierRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/professional': {
      id: '/_authenticated/dashboard/professional'
      path: '/dashboard/professional'
      fullPath: '/dashboard/professional'
      preLoaderRoute: typeof AuthenticatedDashboardProfessionalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/client': {
      id: '/_authenticated/dashboard/client'
      path: '/dashboard/client'
      fullPath: '/dashboard/client'
      preLoaderRoute: typeof AuthenticatedDashboardClientRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/calculator': {
      id: '/_authenticated/dashboard/calculator'
      path: '/dashboard/calculator'
      fullPath: '/dashboard/calculator'
      preLoaderRoute: typeof AuthenticatedDashboardCalculatorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/builder': {
      id: '/_authenticated/dashboard/builder'
      path: '/dashboard/builder'
      fullPath: '/dashboard/builder'
      preLoaderRoute: typeof AuthenticatedDashboardBuilderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/artisan': {
      id: '/_authenticated/dashboard/artisan'
      path: '/dashboard/artisan'
      fullPath: '/dashboard/artisan'
      preLoaderRoute: typeof AuthenticatedDashboardArtisanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/admin-suppliers': {
      id: '/_authenticated/dashboard/admin-suppliers'
      path: '/dashboard/admin-suppliers'
      fullPath: '/dashboard/admin-suppliers'
      preLoaderRoute: typeof AuthenticatedDashboardAdminSuppliersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/admin-settings': {
      id: '/_authenticated/dashboard/admin-settings'
      path: '/dashboard/admin-settings'
      fullPath: '/dashboard/admin-settings'
      preLoaderRoute: typeof AuthenticatedDashboardAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/admin-disputes': {
      id: '/_authenticated/dashboard/admin-disputes'
      path: '/dashboard/admin-disputes'
      fullPath: '/dashboard/admin-disputes'
      preLoaderRoute: typeof AuthenticatedDashboardAdminDisputesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/admin-boq': {
      id: '/_authenticated/dashboard/admin-boq'
      path: '/dashboard/admin-boq'
      fullPath: '/dashboard/admin-boq'
      preLoaderRoute: typeof AuthenticatedDashboardAdminBoqRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/admin': {
      id: '/_authenticated/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof AuthenticatedDashboardAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/projects/$projectId': {
      id: '/_authenticated/dashboard/projects/$projectId'
      path: '/dashboard/projects/$projectId'
      fullPath: '/dashboard/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedDashboardProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/boq-request/$projectId': {
      id: '/_authenticated/dashboard/boq-request/$projectId'
      path: '/dashboard/boq-request/$projectId'
      fullPath: '/dashboard/boq-request/$projectId'
      preLoaderRoute: typeof AuthenticatedDashboardBoqRequestProjectIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/client/projects/new': {
      id: '/_authenticated/dashboard/client/projects/new'
      path: '/projects/new'
      fullPath: '/dashboard/client/projects/new'
      preLoaderRoute: typeof AuthenticatedDashboardClientProjectsNewRouteImport
      parentRoute: typeof AuthenticatedDashboardClientRoute
    }
  }
}

interface AuthenticatedDashboardClientRouteChildren {
  AuthenticatedDashboardClientProjectsNewRoute: typeof AuthenticatedDashboardClientProjectsNewRoute
}

const AuthenticatedDashboardClientRouteChildren: AuthenticatedDashboardClientRouteChildren =
  {
    AuthenticatedDashboardClientProjectsNewRoute:
      AuthenticatedDashboardClientProjectsNewRoute,
  }

const AuthenticatedDashboardClientRouteWithChildren =
  AuthenticatedDashboardClientRoute._addFileChildren(
    AuthenticatedDashboardClientRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardAdminRoute: typeof AuthenticatedDashboardAdminRoute
  AuthenticatedDashboardAdminBoqRoute: typeof AuthenticatedDashboardAdminBoqRoute
  AuthenticatedDashboardAdminDisputesRoute: typeof AuthenticatedDashboardAdminDisputesRoute
  AuthenticatedDashboardAdminSettingsRoute: typeof AuthenticatedDashboardAdminSettingsRoute
  AuthenticatedDashboardAdminSuppliersRoute: typeof AuthenticatedDashboardAdminSuppliersRoute
  AuthenticatedDashboardArtisanRoute: typeof AuthenticatedDashboardArtisanRoute
  AuthenticatedDashboardBuilderRoute: typeof AuthenticatedDashboardBuilderRoute
  AuthenticatedDashboardCalculatorRoute: typeof AuthenticatedDashboardCalculatorRoute
  AuthenticatedDashboardClientRoute: typeof AuthenticatedDashboardClientRouteWithChildren
  AuthenticatedDashboardProfessionalRoute: typeof AuthenticatedDashboardProfessionalRoute
  AuthenticatedDashboardSupplierRoute: typeof AuthenticatedDashboardSupplierRoute
  AuthenticatedDashboardSupplierOnboardingRoute: typeof AuthenticatedDashboardSupplierOnboardingRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardBoqRequestProjectIdRoute: typeof AuthenticatedDashboardBoqRequestProjectIdRoute
  AuthenticatedDashboardProjectsProjectIdRoute: typeof AuthenticatedDashboardProjectsProjectIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardAdminRoute: AuthenticatedDashboardAdminRoute,
  AuthenticatedDashboardAdminBoqRoute: AuthenticatedDashboardAdminBoqRoute,
  AuthenticatedDashboardAdminDisputesRoute:
    AuthenticatedDashboardAdminDisputesRoute,
  AuthenticatedDashboardAdminSettingsRoute:
    AuthenticatedDashboardAdminSettingsRoute,
  AuthenticatedDashboardAdminSuppliersRoute:
    AuthenticatedDashboardAdminSuppliersRoute,
  AuthenticatedDashboardArtisanRoute: AuthenticatedDashboardArtisanRoute,
  AuthenticatedDashboardBuilderRoute: AuthenticatedDashboardBuilderRoute,
  AuthenticatedDashboardCalculatorRoute: AuthenticatedDashboardCalculatorRoute,
  AuthenticatedDashboardClientRoute:
    AuthenticatedDashboardClientRouteWithChildren,
  AuthenticatedDashboardProfessionalRoute:
    AuthenticatedDashboardProfessionalRoute,
  AuthenticatedDashboardSupplierRoute: AuthenticatedDashboardSupplierRoute,
  AuthenticatedDashboardSupplierOnboardingRoute:
    AuthenticatedDashboardSupplierOnboardingRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedDashboardBoqRequestProjectIdRoute:
    AuthenticatedDashboardBoqRequestProjectIdRoute,
  AuthenticatedDashboardProjectsProjectIdRoute:
    AuthenticatedDashboardProjectsProjectIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ImpactRoute: ImpactRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ProblemRoute: ProblemRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  WhyRoute: WhyRoute,
  ConstructionSlugRoute: ConstructionSlugRoute,
  LegalSlugRoute: LegalSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
