/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as LegalSlugRouteImport } from './routes/legal.$slug'
import { Route as ConstructionSlugRouteImport } from './routes/construction.$slug'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardSupplierRouteImport } from './routes/_authenticated/dashboard.supplier'
import { Route as AuthenticatedDashboardProfessionalRouteImport } from './routes/_authenticated/dashboard.professional'
import { Route as AuthenticatedDashboardClientRouteImport } from './routes/_authenticated/dashboard/client'
import { Route as AuthenticatedDashboardCalculatorRouteImport } from './routes/_authenticated/dashboard.calculator'
import { Route as AuthenticatedDashboardBuilderRouteImport } from './routes/_authenticated/dashboard.builder'
import { Route as AuthenticatedDashboardAdminRouteImport } from './routes/_authenticated/dashboard.admin'
import { Route as AuthenticatedDashboardProjectsProjectIdRouteImport } from './routes/_authenticated/dashboard.projects.$projectId'
import { Route as AuthenticatedDashboardClientProjectsNewRouteImport } from './routes/_authenticated/dashboard/client/projects/new'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstructionSlugRoute = ConstructionSlugRouteImport.update({
  id: '/construction/$slug',
  path: '/construction/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardSupplierRoute =
  AuthenticatedDashboardSupplierRouteImport.update({
    id: '/supplier',
    path: '/supplier',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProfessionalRoute =
  AuthenticatedDashboardProfessionalRouteImport.update({
    id: '/professional',
    path: '/professional',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardClientRoute =
  AuthenticatedDashboardClientRouteImport.update({
    id: '/client',
    path: '/client',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCalculatorRoute =
  AuthenticatedDashboardCalculatorRouteImport.update({
    id: '/calculator',
    path: '/calculator',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBuilderRoute =
  AuthenticatedDashboardBuilderRouteImport.update({
    id: '/builder',
    path: '/builder',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdminRoute =
  AuthenticatedDashboardAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProjectsProjectIdRoute =
  AuthenticatedDashboardProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardClientProjectsNewRoute =
  AuthenticatedDashboardClientProjectsNewRouteImport.update({
    id: '/projects/new',
    path: '/projects/new',
    getParentRoute: () => AuthenticatedDashboardClientRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/construction/$slug': typeof ConstructionSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/builder': typeof AuthenticatedDashboardBuilderRoute
  '/dashboard/calculator': typeof AuthenticatedDashboardCalculatorRoute
  '/dashboard/client': typeof AuthenticatedDashboardClientRouteWithChildren
  '/dashboard/professional': typeof AuthenticatedDashboardProfessionalRoute
  '/dashboard/supplier': typeof AuthenticatedDashboardSupplierRoute
  '/dashboard/projects/$projectId': typeof AuthenticatedDashboardProjectsProjectIdRoute
  '/dashboard/client/projects/new': typeof AuthenticatedDashboardClientProjectsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/construction/$slug': typeof ConstructionSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/builder': typeof AuthenticatedDashboardBuilderRoute
  '/dashboard/calculator': typeof AuthenticatedDashboardCalculatorRoute
  '/dashboard/client': typeof AuthenticatedDashboardClientRouteWithChildren
  '/dashboard/professional': typeof AuthenticatedDashboardProfessionalRoute
  '/dashboard/supplier': typeof AuthenticatedDashboardSupplierRoute
  '/dashboard/projects/$projectId': typeof AuthenticatedDashboardProjectsProjectIdRoute
  '/dashboard/client/projects/new': typeof AuthenticatedDashboardClientProjectsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/construction/$slug': typeof ConstructionSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/_authenticated/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/_authenticated/dashboard/builder': typeof AuthenticatedDashboardBuilderRoute
  '/_authenticated/dashboard/calculator': typeof AuthenticatedDashboardCalculatorRoute
  '/_authenticated/dashboard/client': typeof AuthenticatedDashboardClientRouteWithChildren
  '/_authenticated/dashboard/professional': typeof AuthenticatedDashboardProfessionalRoute
  '/_authenticated/dashboard/supplier': typeof AuthenticatedDashboardSupplierRoute
  '/_authenticated/dashboard/projects/$projectId': typeof AuthenticatedDashboardProjectsProjectIdRoute
  '/_authenticated/dashboard/client/projects/new': typeof AuthenticatedDashboardClientProjectsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/dashboard'
    | '/construction/$slug'
    | '/legal/$slug'
    | '/services/$slug'
    | '/dashboard/admin'
    | '/dashboard/builder'
    | '/dashboard/calculator'
    | '/dashboard/client'
    | '/dashboard/professional'
    | '/dashboard/supplier'
    | '/dashboard/projects/$projectId'
    | '/dashboard/client/projects/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/dashboard'
    | '/construction/$slug'
    | '/legal/$slug'
    | '/services/$slug'
    | '/dashboard/admin'
    | '/dashboard/builder'
    | '/dashboard/calculator'
    | '/dashboard/client'
    | '/dashboard/professional'
    | '/dashboard/supplier'
    | '/dashboard/projects/$projectId'
    | '/dashboard/client/projects/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/contact'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/construction/$slug'
    | '/legal/$slug'
    | '/services/$slug'
    | '/_authenticated/dashboard/admin'
    | '/_authenticated/dashboard/builder'
    | '/_authenticated/dashboard/calculator'
    | '/_authenticated/dashboard/client'
    | '/_authenticated/dashboard/professional'
    | '/_authenticated/dashboard/supplier'
    | '/_authenticated/dashboard/projects/$projectId'
    | '/_authenticated/dashboard/client/projects/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  ConstructionSlugRoute: typeof ConstructionSlugRoute
  LegalSlugRoute: typeof LegalSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construction/$slug': {
      id: '/construction/$slug'
      path: '/construction/$slug'
      fullPath: '/construction/$slug'
      preLoaderRoute: typeof ConstructionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/supplier': {
      id: '/_authenticated/dashboard/supplier'
      path: '/supplier'
      fullPath: '/dashboard/supplier'
      preLoaderRoute: typeof AuthenticatedDashboardSupplierRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/professional': {
      id: '/_authenticated/dashboard/professional'
      path: '/professional'
      fullPath: '/dashboard/professional'
      preLoaderRoute: typeof AuthenticatedDashboardProfessionalRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/client': {
      id: '/_authenticated/dashboard/client'
      path: '/client'
      fullPath: '/dashboard/client'
      preLoaderRoute: typeof AuthenticatedDashboardClientRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/calculator': {
      id: '/_authenticated/dashboard/calculator'
      path: '/calculator'
      fullPath: '/dashboard/calculator'
      preLoaderRoute: typeof AuthenticatedDashboardCalculatorRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/builder': {
      id: '/_authenticated/dashboard/builder'
      path: '/builder'
      fullPath: '/dashboard/builder'
      preLoaderRoute: typeof AuthenticatedDashboardBuilderRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/admin': {
      id: '/_authenticated/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof AuthenticatedDashboardAdminRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/projects/$projectId': {
      id: '/_authenticated/dashboard/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/dashboard/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedDashboardProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/client/projects/new': {
      id: '/_authenticated/dashboard/client/projects/new'
      path: '/projects/new'
      fullPath: '/dashboard/client/projects/new'
      preLoaderRoute: typeof AuthenticatedDashboardClientProjectsNewRouteImport
      parentRoute: typeof AuthenticatedDashboardClientRoute
    }
  }
}

interface AuthenticatedDashboardClientRouteChildren {
  AuthenticatedDashboardClientProjectsNewRoute: typeof AuthenticatedDashboardClientProjectsNewRoute
}

const AuthenticatedDashboardClientRouteChildren: AuthenticatedDashboardClientRouteChildren =
  {
    AuthenticatedDashboardClientProjectsNewRoute:
      AuthenticatedDashboardClientProjectsNewRoute,
  }

const AuthenticatedDashboardClientRouteWithChildren =
  AuthenticatedDashboardClientRoute._addFileChildren(
    AuthenticatedDashboardClientRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAdminRoute: typeof AuthenticatedDashboardAdminRoute
  AuthenticatedDashboardBuilderRoute: typeof AuthenticatedDashboardBuilderRoute
  AuthenticatedDashboardCalculatorRoute: typeof AuthenticatedDashboardCalculatorRoute
  AuthenticatedDashboardClientRoute: typeof AuthenticatedDashboardClientRouteWithChildren
  AuthenticatedDashboardProfessionalRoute: typeof AuthenticatedDashboardProfessionalRoute
  AuthenticatedDashboardSupplierRoute: typeof AuthenticatedDashboardSupplierRoute
  AuthenticatedDashboardProjectsProjectIdRoute: typeof AuthenticatedDashboardProjectsProjectIdRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAdminRoute: AuthenticatedDashboardAdminRoute,
    AuthenticatedDashboardBuilderRoute: AuthenticatedDashboardBuilderRoute,
    AuthenticatedDashboardCalculatorRoute:
      AuthenticatedDashboardCalculatorRoute,
    AuthenticatedDashboardClientRoute:
      AuthenticatedDashboardClientRouteWithChildren,
    AuthenticatedDashboardProfessionalRoute:
      AuthenticatedDashboardProfessionalRoute,
    AuthenticatedDashboardSupplierRoute: AuthenticatedDashboardSupplierRoute,
    AuthenticatedDashboardProjectsProjectIdRoute:
      AuthenticatedDashboardProjectsProjectIdRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  ConstructionSlugRoute: ConstructionSlugRoute,
  LegalSlugRoute: LegalSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
